-- ==============================================================================
-- SCRIPT COMPLETO E DEFINITIVO: TABELA solicitacoes_comercial NO SUPABASE
-- ==============================================================================

-- 1. Remove qualquer versão anterior da tabela para começar 100% limpo
DROP TABLE IF EXISTS public.solicitacoes_comercial CASCADE;

-- 2. Cria a tabela com todas as colunas necessárias
CREATE TABLE public.solicitacoes_comercial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    empresa TEXT,
    servico TEXT NOT NULL,
    prazo TEXT,
    desafio TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Novo',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Concede permissões básicas de acesso ao PostgreSQL para a tabela e sequências
GRANT ALL ON TABLE public.solicitacoes_comercial TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 4. Habilita o Row Level Security (RLS)
ALTER TABLE public.solicitacoes_comercial ENABLE ROW LEVEL SECURITY;

-- 5. POLÍTICA PÚBLICA (INSERT): Permite que qualquer pessoa (público / anon) envie o formulário
CREATE POLICY "permitir_envio_anonimo"
    ON public.solicitacoes_comercial
    FOR INSERT
    TO public
    WITH CHECK (true);

-- 6. POLÍTICA ADMINISTRADOR (SELECT, UPDATE, DELETE): Acesso total para usuários logados
CREATE POLICY "permitir_gestao_autenticados"
    ON public.solicitacoes_comercial
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- 7. Cria índice para carregar o painel administrativo rapidamente ordenado por data
CREATE INDEX idx_solicitacoes_comercial_created_at
    ON public.solicitacoes_comercial (created_at DESC);

-- 8. Recarrega o cache do PostgREST imediatamente
NOTIFY pgrst, 'reload schema';
