/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ComoTrabalhamosRouteImport } from './routes/como-trabalhamos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EngenhariaAutomacaoRouteImport } from './routes/engenharia-automacao'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SolucoesDigitaisRouteImport } from './routes/solucoes-digitais'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoTrabalhamosRoute = ComoTrabalhamosRouteImport.update({
  id: '/como-trabalhamos',
  path: '/como-trabalhamos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaAutomacaoRoute = EngenhariaAutomacaoRouteImport.update({
  id: '/engenharia-automacao',
  path: '/engenharia-automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesDigitaisRoute = SolucoesDigitaisRouteImport.update({
  id: '/solucoes-digitais',
  path: '/solucoes-digitais',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cases': typeof CasesRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contato': typeof ContatoRoute
  '/engenharia-automacao': typeof EngenhariaAutomacaoRoute
  '/sobre': typeof SobreRoute
  '/solucoes-digitais': typeof SolucoesDigitaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cases': typeof CasesRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contato': typeof ContatoRoute
  '/engenharia-automacao': typeof EngenhariaAutomacaoRoute
  '/sobre': typeof SobreRoute
  '/solucoes-digitais': typeof SolucoesDigitaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cases': typeof CasesRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contato': typeof ContatoRoute
  '/engenharia-automacao': typeof EngenhariaAutomacaoRoute
  '/sobre': typeof SobreRoute
  '/solucoes-digitais': typeof SolucoesDigitaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/cases'
    | '/como-trabalhamos'
    | '/contato'
    | '/engenharia-automacao'
    | '/sobre'
    | '/solucoes-digitais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/cases'
    | '/como-trabalhamos'
    | '/contato'
    | '/engenharia-automacao'
    | '/sobre'
    | '/solucoes-digitais'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/cases'
    | '/como-trabalhamos'
    | '/contato'
    | '/engenharia-automacao'
    | '/sobre'
    | '/solucoes-digitais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CasesRoute: typeof CasesRoute
  ComoTrabalhamosRoute: typeof ComoTrabalhamosRoute
  ContatoRoute: typeof ContatoRoute
  EngenhariaAutomacaoRoute: typeof EngenhariaAutomacaoRoute
  SobreRoute: typeof SobreRoute
  SolucoesDigitaisRoute: typeof SolucoesDigitaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-trabalhamos': {
      id: '/como-trabalhamos'
      path: '/como-trabalhamos'
      fullPath: '/como-trabalhamos'
      preLoaderRoute: typeof ComoTrabalhamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia-automacao': {
      id: '/engenharia-automacao'
      path: '/engenharia-automacao'
      fullPath: '/engenharia-automacao'
      preLoaderRoute: typeof EngenhariaAutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes-digitais': {
      id: '/solucoes-digitais'
      path: '/solucoes-digitais'
      fullPath: '/solucoes-digitais'
      preLoaderRoute: typeof SolucoesDigitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CasesRoute: CasesRoute,
  ComoTrabalhamosRoute: ComoTrabalhamosRoute,
  ContatoRoute: ContatoRoute,
  EngenhariaAutomacaoRoute: EngenhariaAutomacaoRoute,
  SobreRoute: SobreRoute,
  SolucoesDigitaisRoute: SolucoesDigitaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
