-- ==============================================================================
-- SCRIPT COMPLETO E DEFINITIVO: TABELA solicitacoes_comercial NO SUPABASE
-- ==============================================================================

-- 1. Remove qualquer versão anterior da tabela para começar 100% limpo
DROP TABLE IF EXISTS public.solicitacoes_comercial CASCADE;

-- 2. Cria a tabela com todas as colunas necessárias
CREATE TABLE public.solicitacoes_comercial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    empresa TEXT,
    servico TEXT NOT NULL,
    prazo TEXT,
    desafio TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Novo',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Concede permissões básicas de acesso ao PostgreSQL para a tabela e sequências
GRANT ALL ON TABLE public.solicitacoes_comercial TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 4. Habilita o Row Level Security (RLS)
ALTER TABLE public.solicitacoes_comercial ENABLE ROW LEVEL SECURITY;

-- 5. POLÍTICA PÚBLICA (INSERT): Permite que qualquer pessoa (público / anon) envie o formulário
CREATE POLICY "permitir_envio_anonimo"
    ON public.solicitacoes_comercial
    FOR INSERT
    TO public
    WITH CHECK (true);

-- 6. POLÍTICA ADMINISTRADOR (SELECT, UPDATE, DELETE): Acesso total para usuários logados
CREATE POLICY "permitir_gestao_autenticados"
    ON public.solicitacoes_comercial
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- 7. Cria índice para carregar o painel administrativo rapidamente ordenado por data
CREATE INDEX idx_solicitacoes_comercial_created_at
    ON public.solicitacoes_comercial (created_at DESC);

-- 8. Recarrega o cache do PostgREST imediatamente
NOTIFY pgrst, 'reload schema';

-- ============================================================================
-- BLOG: POSTS E CATEGORIAS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    category TEXT NOT NULL,
    image TEXT,
    full_text TEXT NOT NULL,
    published BOOLEAN NOT NULL DEFAULT true,
    date TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blog_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

GRANT SELECT ON TABLE public.blog_posts, public.blog_categories TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE public.blog_posts, public.blog_categories TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "blog_posts_public_read" ON public.blog_posts;
CREATE POLICY "blog_posts_public_read"
    ON public.blog_posts FOR SELECT TO anon, authenticated
    USING (published = true OR auth.role() = 'authenticated');

DROP POLICY IF EXISTS "blog_posts_authenticated_manage" ON public.blog_posts;
CREATE POLICY "blog_posts_authenticated_manage"
    ON public.blog_posts FOR ALL TO authenticated
    USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "blog_categories_public_read" ON public.blog_categories;
CREATE POLICY "blog_categories_public_read"
    ON public.blog_categories FOR SELECT TO anon, authenticated
    USING (true);

DROP POLICY IF EXISTS "blog_categories_authenticated_manage" ON public.blog_categories;
CREATE POLICY "blog_categories_authenticated_manage"
    ON public.blog_categories FOR ALL TO authenticated
    USING (true) WITH CHECK (true);

INSERT INTO public.blog_categories (name)
VALUES ('Automação'), ('Websites'), ('Software'), ('Projetos elétricos'), ('Inovação')
ON CONFLICT (name) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_blog_posts_created_at
    ON public.blog_posts (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_blog_posts_published
    ON public.blog_posts (published);

NOTIFY pgrst, 'reload schema';
